### ISSUE TITLE
Upgrading from  4.3.0 to version 5.1.0 cause checkpointing error

### ISSUE THREAD

**Issue by macfilion** [Azure/azure-functions-dotnet-worker#1198]
Hi

When upgrading from version 4.3.0 to 5.1.0 we noticed that the storage structure for the checkpointing and the ownership filed changed.

Ownership files are now store in the ownership folder and checkpointing files are now in the checkpoint folder instead of having all the files in the same directory.

With the version 5.1.0 the files for the ownership are created but not the checkpointing files.

In the logs , we are getting a lot of "Function 'functionName': Unable to deserialize partition or lease info with the following errors: Unable to find a checkpoint information for partition: 36 Unable to find a checkpoint information for partition:"

We upgrade 5 of our services, 3 of them work correctly 2 of them are raising this warning and we had to rollback.

Any ideas what is causing that?

Thank you

.net 6
OutputType : exe (isolated)

**Comment by kshyju** [comment]
What package did you upgrade from 4.30 to 5.1.0?

**Comment by macfilion** [comment]
Microsoft.Azure.Functions.Worker.Extensions.EventHubs

**Comment by fabiocav** [comment]
@JoshLove-msft can you please provide some feedback here?

**Comment by JoshLove-msft** [comment]
This was fixed in 5.1.2 - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/CHANGELOG.md#512-2022-08-10

**Comment by kshyju** [comment]
Thanks @JoshLove-msft 

@macfilion Let us know if you still have questions.

**Comment by macfilion** [comment]
hum... the library that cause our problem is Microsoft.Azure.Functions.Worker.Extensions.EventHubs
in the fix provided by @JoshLove-msft it talks about Microsoft.Azure.WebJobs.Extensions.EventHubs

Is this related?

**Comment by kshyju** [comment]
Microsoft.Azure.Functions.Worker.Extensions.EventHubs package is a soft wrapper (_for lack of a better term_) on top of Microsoft.Azure.WebJobs.Extensions.EventHubs package. So any release of the worker package is bringing in the changes of the webjobs version of package. 

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.EventHubs/src/Properties/AssemblyInfo.cs#L6

**Comment by macfilion** [comment]
we are still having the problem.

The is the versionning of the lib when looking at the process monitoring
![image](https://user-images.githubusercontent.com/119060000/208194842-1803fa7d-d203-42c3-b447-33677df1234c.png)

**Comment by kzryzstof** [comment]
@kshyju I do experience the same issue.

Somehow, even if I explicitly reference the 5.1.2 version of the package `Microsoft.Azure.WebJobs.Extensions.Eventhubs` (on top of referencing the package `Microsoft.Azure.Functions.Worker.Extensions.EventHubs` version 5.1.0), I still get the april 2022 version of `Microsoft.Azure.WebJobs.Extensions.Eventhubs.dll` in the `.azurefunction` folder.

<img width="1165" alt="Output folder" src="https://user-images.githubusercontent.com/38137839/211565650-bfcdde3e-5f78-4731-bc7d-ba4bad4ce52d.png">

<img width="498" alt="Referenced packages" src="https://user-images.githubusercontent.com/38137839/211565667-b43232f8-1dfa-4ebe-943e-97c3ded313bb.png">
