### ISSUE TITLE
Indexing issue using OpenAPI extension and latest SDK

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#2084]
Hey @kshyju 

Version wise it looks the same for me, maybe its because i am working on an arm platform instead of an intel?

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/453360/7bc334ef-e25c-40ca-8f80-b1a92b38e33b)

and after adding the env to my docker container i see the function, but they are still returning 404 when calling them

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/453360/1e01e734-cded-4c3e-a5e7-8681b7460711)

and when calling the swagger endpoint i receive this exception

```
      Function 'RenderSwaggerDocument', Invocation id 'e2931646-dd61-464c-811e-dd5d7090b6c9': An exception was thrown by the invocation.
      Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Function 'RenderSwaggerDocument', Invocation id 'e2931646-dd61-464c-811e-dd5d7090b6c9': An exception was thrown by the invocation.
      Exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
         at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
         at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
      Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
         at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
         at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
```

when running without the additional feature flag, i can open the endpoints for swagger now and there is no error, but when calling my own endpoint i receive 404 and there is nothing in the logs as well 🤷‍♂️

if i add

```xml
        <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>
```

to the project i can start the debug session locally and call the endpoint

_Originally posted by @MO2k4 in https://github.com/Azure/azure-functions-dotnet-worker/issues/2062#issuecomment-1814028793_

**Comment by fabiocav** [comment]
@MO2k4 , can you update the repro to reflect the lates state you're validating?

Can you verify whether rebuilding the image (to take in latest tag/image updates) shows a different result here?

We'll go through your repro in the meantime.

**Comment by kshyju** [comment]
Hi @MO2k4

I cloned your [repro ](https://github.com/MO2k4/MinimalRepro.Trigger.In.Nested.Namespaces)again today and built an image using the docker file present in the repo. I was able to see all the endpoints (both from your function app from the open api extension) working as expected. I have pushed that image [here](https://hub.docker.com/r/kshyju/gh-2084-openapi-repro) so that you can also validate on your side.

```bash
docker run -p 8080:80 kshyju/gh-2084-openapi-repro:1
```
then try these URLs.

1. http://localhost:8080/api/swagger.json
2. http://localhost:8080/api/httptrigger (you will see 401 because you have auth enabled on that function)
3. http://localhost:8080/api/swagger/ui


The screenshot you posted above does show the function "HttpTrigger" has a route defined as "/api/foobar". But your repro does not reflect that. I am also not able to replicate the exception you described above when trying to access the "RenderSwaggerDocument" function from the repro you shared.   Can you make sure you are testing what you have shared with us? If you are still experiencing an issue, please let us know with a more accurate repro. Thank you!

**Comment by MO2k4** [comment]
@kshyju @fabiocav sorry i missed to push my latest changes. i can still reproduce the exception during swagger ui load and also the 404 for my own endpoint

@kshyju checking your docker file, leads to the same errors

**Comment by kshyju** [comment]
If you are getting 401 response when accessing `/api/HttpTrigger`, that is expected because your function has `AuthorizationLevel.Function` defined and if you do not pass a valid key, you will get [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401). This is what I mentioned in my previous comment.

Feel free to close the issue if your problems are resolved. If you are still running into issues, please let us know. Thank you!

**Comment by kshyju** [comment]
Can you please be more specific? Where are you getting the error? In azure? What SKU are you deploying? What platform (Windows or Linux)? Do you see same error locally or in a Linux container? If it is only happening in azure when deployed, is your function app totally down because of this error?

**Comment by MO2k4** [comment]
I saw this error after a docker build and running that container locally, but with my real services, after rebuilding everything the error is now gone but now i am receiving

```
fail: Host.Results[0]
      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.GetAllTemplates
       ---> Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException: dotnet exited with code 133 (0x85)
       ---> System.Exception: assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 101
         at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
         at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108
```

i will try to adapt this tomorrow to my repro, sorry that i can't recreate a reproduction for this.

are there any infos you would need from me upfront?

**Setup**
macOS (arm, M2 Max)
func: 4.0.5455
.Net 8.0.100
colima as docker tooling
docker base image: mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0-slimdock sha256:7eda9a94f958d5314b121e623ec79dda4ba4911146d77c06eecdfb8bd48925f3

**Comment by MO2k4** [comment]
for now i am not able to create a reproduction for this error with my sample, but i am seeing this error while testing my real instances locally - when i build everything in a azure devops pipeline (i think its using windows or linux) everything works but locally when using colima, i see this memory errors. my assumption would be that it has something to do with arm vs amd64

**Comment by kshyju** [comment]
@MO2k4 If you are still getting the error locally, I am curious to see your docker file. Can you share that please? Do you see an environment variable called "AzureWebJobsFeatureFlags" with value "EnableWorkerIndexing" inside your container? If not, can you add that?

**Comment by MO2k4** [comment]
Hey @kshyju yeah i am still seeing this error locally but i cant produce a reproduction

my dockerfile looks like this:

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base

ENV PATH="$PATH:/root/.dotnet/tools"

RUN set -x && \
    /usr/bin/apt-get update && \
    apt-get install --fix-missing && \
    # Install Java and other tools
    DEBIAN_FRONTEND=noninteractive apt-get install -y default-jre-headless && \
    # Install Sonarqube-Scanner & coverage tool
    dotnet tool install --global dotnet-sonarscanner && \
    # Cleanup
    /usr/bin/apt-get clean && \
    /bin/rm -rf /var/lib/apt/lists/*

ARG sonarLogin=""
ARG sonarHost=""
ARG projectKey=""
ARG currentBranch=""
ARG sourceBranch=""
ARG targetBranch=""
ARG pullRequestId=""
ARG path="."

# execute unit tests
COPY service/*.csproj /src/${path}/service/
COPY test/*.csproj /src/${path}/test/
COPY service/NuGet.Config /src/NuGet.Config

WORKDIR /src/

RUN dotnet new sln && \
    find . -name '*.csproj' | xargs dotnet sln add $1 >> /dev/null 2>&1  && \
    dotnet restore src.sln

COPY service/ /src/${path}/service/
COPY test/ /src/${path}/test/
COPY integration.test/ /src/${path}/integration.test/

LABEL test=true

RUN \
if [ -n "$pullRequestId" ] && [ "$pullRequestId" -eq "$pullRequestId" ] 2>/dev/null; \
then \
  echo 'Execute pull request build' && \
  dotnet sonarscanner begin /k:${projectKey} \
    /d:sonar.host.url=${sonarHost} \
    /d:sonar.login=${sonarLogin} \
    /d:sonar.pullrequest.key=${pullRequestId} \
    /d:sonar.pullrequest.branch=${sourceBranch} \
    /d:sonar.pullrequest.base=${targetBranch} \
    /d:sonar.cs.opencover.reportsPaths=/testresults/**/coverage.opencover.xml \
    /d:sonar.cs.vstest.reportsPaths=/testresults/**/test_results.xml \
    /d:sonar.projectBaseDir=/src/ \
    /d:sonar.sourceEncoding=UTF-8 \
    /d:sonar.scm.disabled=true; \
  dotnet build src.sln --no-restore && \
  dotnet test "${path}/test" \
    --no-build \
    --no-restore \
    --results-directory /testresults/ \
    --logger "trx;LogFileName=test_results.xml" \
    --logger "junit;LogFileName=test_results.junit.xml" \
    /p:CollectCoverage=true \
    /p:CoverletOutput=/testresults/ \
    /p:CoverletOutputFormat=\"cobertura,opencover\" && \
  (dotnet sonarscanner end /d:sonar.login=${sonarLogin} || exit 0); \
else \
  echo 'Execute branch build' && \
  dotnet sonarscanner begin /k:${projectKey} \
    /d:sonar.host.url=${sonarHost} \
    /d:sonar.login=${sonarLogin} \
    /d:sonar.branch.name=${currentBranch} \
    /d:sonar.cs.opencover.reportsPaths=/testresults/**/coverage.opencover.xml \
    /d:sonar.cs.vstest.reportsPaths=/testresults/**/test_results.xml \
    /d:sonar.projectBaseDir=/src/ \
    /d:sonar.sourceEncoding=UTF-8 \
    /d:sonar.scm.disabled=true; \
  dotnet build src.sln --no-restore && \
  dotnet test "${path}/test" \
    --no-build \
    --no-restore \
    --results-directory /testresults/ \
    --logger "trx;LogFileName=test_results.xml" \
    --logger "junit;LogFileName=test_results.junit.xml" \
    /p:CollectCoverage=true \
    /p:CoverletOutput=/testresults/ \
    /p:CoverletOutputFormat=\"cobertura,opencover\" && \
  (dotnet sonarscanner end /d:sonar.login=${sonarLogin} || exit 0); \
fi

# publish: build and package dependencies
RUN cd /src/${path}/service && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot --no-restore

FROM base as integration-test
WORKDIR /src/${path}/integration.test
CMD dotnet test

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0-slim as prod

ENV AzureWebJobsScriptRoot=/home/site/wwwroot
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true
ENV AzureWebJobsDisableHomepage="true"
ENV AzureWebJobsFeatureFlags=EnableWorkerIndexing

RUN apt-get install procps -y

COPY --from=base ["/home/site/wwwroot", "/home/site/wwwroot"]
COPY --from=base ["/testresults", "/testresults"]

COPY start.sh /azure-functions-host/start.sh
CMD ["bash", "/azure-functions-host/start.sh"]
```

**Comment by kshyju** [comment]
It's hard for me to tell you what exactly is causing the error for you. I created a minimal .NET8 app with docker support [here](https://github.com/kshyju/MoreDotnetIsolatedSamples/tree/master/Net8WithDocker). Can you compare your app with this and see that helps you to narrow down your issue?
