### ISSUE TITLE
Azure Functions in dotnet-isolated for ServiceBusTriggers for .NET7 are not firing unless opened in portal

### ISSUE THREAD

**Issue by momcina08** [Azure/azure-functions-dotnet-worker#2202]
Hello,

I have about 15 to 20 AzureFunctions in Serverless plan that need to be triggered by service bus message. Unfortunatelly my functions are never invoked unless i opet the Function App inside the ResourceGroup. Is there any way to resolve this?
i have these settings set for my function app:
FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED: 1
WEBSITE_ENABLE_SYNC_UPDATE_SITE: 1
FUNCTIONS_EXTENSION_VERSION: ~4
WEBSITE_RUN_FROM_PACKAGE: 1

**Comment by kshyju** [comment]
Hi @momcina08  

1. Did this start after a deployment from your side? If so, what change was in the deployment for the function app?  
2. What version of package are you using? 
3. What SKU are you experiencing this issue?

If you can share your app information, we can take a look. Please see "[Sharing Your Function App name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)"

**Comment by momcina08** [comment]
1. Deployment didn't affect it, i always need to do that.
2. I don't understand what you mean by package? i deploy it as zip if that is the question
3. All function apps are Linux and serverless, i have about 20 function apps and this behavior is the same for all of them, all supposed to be triggered by ServiceBusTrigger.

**Comment by savbace** [comment]
I am experiencing the same issue. My setup:
- NET 7 Isolated 64 Bit
- Runtime v4
- Windows
- Microsoft.Azure.Functions.Worker 1.20.0
- Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.15.0
- Microsoft.Azure.Functions.Worker.Sdk 1.16.4

**Comment by Bandgren** [comment]
@savbace, @kshyju.

I have experiencing this exact same issue over the last couple of days! I managed to get it fixed by downgrading the  Microsoft.Azure.Functions.Worker.Sdk from 1.16.4 down to 1.15.1 so there seem to be some sort of incompadability with the scaler or something. This issue happens when the function host instance goes into idle. Then it never wakes up again on the 1.16.4 SDK version unless you open it in the portal to kick it alive again.

I added this app setting to the some logs from the scaler: `SCALE_CONTROLLER_LOGGING_ENABLED=AppInsights:Verbose`.

Before the downgrade with the scale logger enable we see this in the logs:
<img width="1624" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/53816703/69af2bdc-3c93-444c-9131-e8a46f0aedae">

at 6:06 the function goes into idle, at 6:25 i put messages on the topic and nothing happens, at 6:30 i go to the function in the portal and everything starts up.

If we now see the logs from after the downgrade to 1.15.1:
<img width="1073" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/53816703/1ca733ff-445a-4d09-96fc-08c2ca0bdadf">

We see that at 8:19:03 we go into idle, and its stopped. But we can now see that the scaler keeps pooling the SB to see if it need to start up. And when i put a message into the topic it triggers right away!

So there seems to be some regression bug or something happening on the 1.16.* package! I can see that there is already 1.17 previews. Hopefully we can get some attention on this one and get it fixed ASAP!

**Comment by kshyju** [comment]
We recently Identified a regression which impacted the scaling components. The [issue was fixed](https://github.com/Azure/azure-functions-dotnet-worker/pull/2234) and the latest stable version of Worker.Sdk package includes that fix.

@momcina08 / @Bandgren Could you please upgrade to [Microsoft.Azure.Functions.Worker.Sdk 1.17.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.0)? Please keep us posted how that goes.

**Comment by dvdgutzmann** [comment]
Just to improve searchability for others with my specs. Upgrading `Microsoft.Azure.Functions.Worker.Sdk` to _1.17.0_ also made all my problems go away. I have NET 8 dotnet-isolated functions running on a consumption plan and not being triggered on a service bus trigger once the scale controller had kicked the last instance . 

I was under the impression NET 8 isolated-workers were the propagated way forward, would've expected Microsoft to have some decent integration tests around the new and shiny.  I just spend two days with this (and https://github.com/Azure/azure-functions-dotnet-worker/issues/2270, which is still broken by the way, hint,  hint)

**Comment by mr-davidc** [comment]
Hi @dvdgutzmann,

Were there any other changes you needed to do to get it working ? I have tried updating `Microsoft.Azure.Functions.Worker.Sdk` to `1.17.1` in my NET 8 Isolated project but it still doesn't trigger the function for me.

**Comment by Angelm116** [comment]
Hello @kshyju, 

I am still seeing this issue with Microsoft.Azure.Functions.Worker.Sdk 1.17.4. Any ideas on what to try?

**Comment by jstenlund** [comment]
@Angelm116 We have observed the same issue with service bus triggers in several instances since upgrading from .NET 6 in-process to .NET 8 isolated. The version of Microsoft.Azure.Functions.Worker.Sdk is 1.17.0. What seems to have fixed the problem is enabling Always On for the function apps. It would be interesting to know if this makes a difference for others as well.
