### ISSUE TITLE
Function app  - Encountered an error (InternalServerError) from host runtime.

### ISSUE THREAD

**Issue by ganiths** [Azure/azure-functions-dotnet-worker#2409]
### Description

Recently migrated my functions from .NET 6 in process to .NET isolated workers. Deployed the Functions to Azure and all my functions  are invoked succesfully. But in azure portal am  seeing an error "Encountered an error (InternalServerError) from host runtime" when i click on below pages

1. In over view page , displaying an error **Error while loading functions  "Encountered an error (InternalServerError) from host runtime"** even though all functions are listed in that page
2. In App keys page ,  , displaying an error **Error while loading functions  "Encountered an error (InternalServerError) from host runtime"** but no keys are displayed

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12411191/80f655df-1ec4-4057-ac08-06d865abcc31)

3 In Activity log, its showing SyncWeb apps function trigger and list host keys as failed

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12411191/a73facb5-14c2-4462-9646-3f9a3e98e65d)

with status message as below

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12411191/cc87f098-8574-4e04-b383-6f83c67e6bdb)

My project uses below references

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12411191/0a9ea9ff-8b39-489b-9fe9-b7789bf65662)

Raised a support ticket with Microsoft on Azure. So far they were not able to identity it

Has anyone encountered a similar issue with isolated worker  function apps? If so, how did you resolved it?

### Steps to reproduce

Refer the description

**Comment by liliankasem** [comment]
Hi @ganiths, are there any new updates from the support ticket you raised?

**Comment by ganiths** [comment]
@liliankasem 

Based on the investigation by Microsoft support team, below change is made in  azure portal recently 

**a recent experience change to highlight an issue in the portal in synchronizing the list of functions to avoid showing stale data. The logic was updated in a way so that if there are synchronization issues, the latest cached list of functions in your function app will be shown in addition to any error messages which may have come from a synchronization operation.  This is done to allow customers to continue operating on their existing functions while also raising awareness for any potential issues with their Function App.**

Due to this change,  host runtime was sending request to function app  endpoint url to find out what functions are available and display the same in the portal

In my case, my function app was not publicly accessible and accessible only over private endpoint. Since i was not allowing the traffic between the  function app outbound integration subnet and inbound private endpoint subnet, i was getting an error "Internal server error"

After updating the NSG rule sto allow the traffic, error goes away in the portal.

Above error was not specific to isolated worker, it even happens for in-process app as well.

**Comment by haovanvo** [comment]
I encountered same issue but different root cause. My problem is that the AzureWebJobsStorage environment variable is setting to none accessible storage account. After granted access permission for the Function App to access the storage then the issue was gone.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/7547579/dc03248e-ed2a-4902-b849-2782a0157f03)

**Comment by liliankasem** [comment]
Thank you for sharing the details, it sounds like this was a configuration issue to do with either network or permissions. Can we consider this issue resolved?

**Comment by ganiths** [comment]
@liliankasem Yes,the issue is resolved and can be closed

**Comment by nadershamma** [comment]
I am now experiencing this issue with one of our prod deployments. Nothing changed and then 3 days ago the app stopped working. I've torn down the linux hosted instance, changed it to windows and still the same issue. The last deployment was in April this year.

**Comment by liliankasem** [comment]
Hi, if you're experiencing a similar issue, please open an azure support ticket. For anything production related a support ticket is required for the product team to investigate your application. Thanks!
