### ISSUE TITLE
Is Linux supported?

### ISSUE THREAD

**Issue by pascal-hauser** [Azure/azure-functions-dotnet-worker#336]
# Problem
A TimerTrigger function doesn't get executed for Linux platform.

# Details
When I create the functionapp as described in the secriont Deploy to Azure in the Readme I get the error:
`The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one.`

When i add the parameter `--os-type Linux` the functionapp can be created. But then when I publish the functionapp I get the following output:
```
...
Getting site publishing info...
Uploading package...
Uploading 1.81 MB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Functions in {}:
    TimedImportTrigger - [No Trigger Found]
```

 I assume `No Trigger Found` is not the expected response.

# Additional Info
- The function is a TimerTrigger function.
- The functionapp was created with `--runtime dotnet-isolated` whereas the Readme states `--runtime dotnet`. Changed as `dotnet` leads to a warning.
- Locally the function runs successfully through `func host start`.

**Comment by balag0** [comment]
Please share the app name - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by pascal-hauser** [comment]
As per Option 2, I sent a request as described which resultet in a 404.
Guid: 81AFFA4D-BC34-4AE9-9D6A-21341A09F6EA
Time: Around 07:45:00 UTC Wednesday, 24 March 2021
Region: Switzerland North

**Comment by balag0** [comment]
Thanks. 

@ankitkumarr FYI
Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover

**Comment by balag0** [comment]
@pascal-hauser This should be working now. Could you please give it a try?

**Comment by pascal-hauser** [comment]
Thank you @balag0. When I publish the function now the output successfully shows:
```
Functions in {}:
    TimedImportTrigger - [TimerTrigger]
```
Also when I check in the Azure portal under the `[MyFunctionApp] -> Functions/Functions -> [TimedImportTrigger] -> Integration` I see the Trigger and see that the Schedule is synced with what's specified in the code. That part seems to work good now.

Unfortunately the function still doesn't get executed. Even when I set the `[TimerTrigger("0 * * * * *")]`, which then should execute every minute, under the 'Monitor' tab of the TimedImportTrigger there are no 'Invocation Traces' listed, also neither 'Application Insights' nor 'Log stream' report any execution. Any idea?

Also, just for information, was this a general issue that is permanently fixed or something specific to the Function App instance that might happen to others too?

Thank you!

**Comment by balag0** [comment]
It was an issue with that region where we didn't have the latest functions runtime images deployed. It would have impacted other apps as well. 

We can confirm this app is now using the correct image, so the failures need more investigation

@ankitkumarr Could you please take a look at this. Verified the app is using host version 3.0.15417, so the deployment issue should be fixed now but we still seem to be having the below error.

PreciseTimeStamp | RoleInstance | Summary | Details
-- | -- | -- | --
2021-03-31 18:08:12.6948335 | App-41E5AAC2-637527956964771370 | Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover |

**Comment by ankitkumarr** [comment]
Thanks @balag0 for the investigation.

Looks like the worker fails with exit code 134 --
"Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException: dotnet exited with code 134"

@pascal-hauser, would you be able to share your code or a repro with us for further investigation?

cc: @fabiocav if you have any thoughts or input here.

**Comment by fabiocav** [comment]
Some ideas, but would need to look at the application logs to confirm. The project would also help. @pascal-hauser are you using self contained or Ready to Run with your deployed app?

**Comment by pascal-hauser** [comment]
@fabiocav it's a 'Ready to Run' app. With the hint from your comment I also deployed it as a self-contained app, but this also doesn't show any executions.
As of application logs, I didn't find any. Under Function->Monitor->Logs the portal connects to Application Insights but doesn't show anything. `func azure functionapp logstream <appname>` shows `Log stream is not currently supported in Linux Consumption Apps.`
I added the sample project.
[Sample.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/6273000/Sample.zip)

**Comment by fabiocav** [comment]
@pascal-hauser what RID are you using when you publish the app?

**Comment by pascal-hauser** [comment]
@fabiocav, when I tried to publish as self contained I was publishing it as linux-x64. Is this the right one or what would be correct? Did it work for you? Where would one find the application logs that you mentioned earlier?

**Comment by fabiocav** [comment]
We'll work on a sample for ready to run / self contained so we can both, validate the scenario and have better guidance here. 

Does everything work for you when deploying as portable (not self-contained/R2R)?

/cc @brettsam

**Comment by fabiocav** [comment]
@pascal-hauser we're in sprint planning and trying to close on this item. Can you confirm the RID and steps you ran through so we can validate the scenario? Thanks!
