### ISSUE TITLE
Exception handling middleware example not behaving as expected

### ISSUE THREAD

**Issue by Alan-Hinton** [Azure/azure-functions-dotnet-worker#936]
I have copied the exception handling sample from here https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/ExceptionHandlingMiddleware.cs however the result I get it not as I would expect.  I am getting the whole HttpResponse object back as json in the body of the response. The actual data I pass in to `WriteAsJsonAsync` is appearing Base64 encoded in the `body` property of the response.  Also the response code is always 200, rather than the value I set.

e.g. I am seeing the **body** of response as follows:
```
{
  "method": "",
  "query": {},
  "statusCode": "400",
  "headers": {
    "Content-Type": "application/json; charset=utf-8"
  },
  "enableContentNegotiation": false,
  "cookies": [],
  "body": "eyJtZXNzYWdlIjoi...dCBleGlzdC4ifV19fQ=="
}
```
Passing my desired response object directly into the InvocationResult Value does give me the expected response body and seems much simpler.

However neither method seems to enable me to set the response status code.

**Comment by kshyju** [comment]
Hi @Alan-Hinton 

The `HttpRequestData.CreateResponse` method creates an instance of `HttpResponseData` with the default status code, which is 200 OK. That is the reason you are seeing the JSON data as the result with 200 OK response status code. If you want to return a different status code, use a [the overload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httprequestdataextensions.createresponse?view=azure-dotnet) which takes the HttpStatusCode value.

Keep in mind that, the `WriteAsJsonAsync` overload you are using will not use the status code of the `HttpResponseData` instance you are passing to it, due to [this known issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/776).  We plan on fixing that in the next major release of the worker package. Until then, you need to use the overload which takes the status code.

The below sample will produce a response with 500 status code.
````
var httpReqData = await context.GetHttpRequestDataAsync();
if (httpReqData != null)
{
    var newHttpResponse = httpReqData.CreateResponse(HttpStatusCode.InternalServerError);
    await newHttpResponse.WriteAsJsonAsync(new { FooStatus = "Failed!" }, newHttpResponse.StatusCode);

    // Update invocation result.
    context.GetInvocationResult().Value = newHttpResponse;
}
````

We will update the sample to avoid the confusion. Thanks!  Let us know if you still run into issues.

**Comment by Alan-Hinton** [comment]
The above method is showing the same behaviour for me i.e. I am getting the whole HttpResponseData object returned as the body of the response and I am still getting a 200 response code.

**Comment by kshyju** [comment]
Can you share a minimal repro in a GitHub repo link?

**Comment by Alan-Hinton** [comment]
If I do curl in verbose mode then the problem is clearer
```
curl -X POST "http://localhost:7071/api/throw-exception" -H  "accept: */*" -d "" -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:7071...
* Connected to localhost (127.0.0.1) port 7071 (#0)
> POST /api/throw-exception HTTP/1.1
> Host: localhost:7071
> User-Agent: curl/7.79.1
> accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 196
< Content-Type: application/json; charset=utf-8
< Date: Tue, 21 Jun 2022 15:41:19 GMT
< Server: Kestrel
<
{"method":"","query":{},"statusCode":"404","headers":{"Content-Type":"application/json; charset=utf-8"},"enableContentNegotiation":false,"cookies":[],"body":"eyJNZXNzYWdlIjoiVGVzdCBtZXNzYWdlIn0="}* Connection #0 to host localhost left intact
```
You can see it is returning a 200 status and then the full HttpRequestData object as json.  That json does happens to include a value called 'status code' with the value 404, but that is not the status of the result i.e. standard web clients would not see that result.  I expect it to just return the object passed to WriteAsJsonAsync i.e. the exception message "Test Message".

**Comment by kshyju** [comment]
Took another look at the issue. You are not getting the desired behavior(404 status code for http response and exception message as the body of the response) because you are not using the correct return type for your http trigger function. You are using `void` as the return type for the `ThrowException` method. If you want to return a valid http response from your function, you should use [HttpResponseData](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httpresponsedata?view=azure-dotnet) as the return type of your function.

The below code should work.

````
[Function("ThrowException")]
public HttpResponseData ThrowException(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception")] HttpRequestData req)
    => throw new System.Exception("Test message");
````

My previous comment was based on testing with the incorrect function code(with void as return type) 🤦

Let us know if you still run into issues. We will consider adding an analyzer to prevent users from using incorrect return types, in the future.

**Comment by elsand** [comment]
The issue regarding multiple bindings was mentioned in https://github.com/Azure/azure-functions-dotnet-worker/issues/530#issuecomment-1011712725, but not addressed in the PR that was accepted. The proposed workaround has to make assumptions about the field names used in the complex type returned for the function, as PropertyOutputBindingsInfo does not include any type information (only names of properties in the privat field `_propertyNames`).

So based on the code from the aforementioned comment, one could do something like this hack:

```
public static class FunctionContextExtensions 
{
    public static void SetInvocationResult(this FunctionContext context, HttpResponseData response)
    {
        var keyValuePair = context.Features.SingleOrDefault(f => f.Key.Name == "IFunctionBindingsFeature");
        var functionBindingsFeature = keyValuePair.Value;
        var bindingFeatureType = functionBindingsFeature.GetType();
        
        var outputBindingsInfo = bindingFeatureType
            .GetProperty("OutputBindingsInfo")!
            .GetValue(functionBindingsFeature);
        var outputPropertyNames = (List<string>?)outputBindingsInfo?
            .GetType()
            .GetField("_propertyNames", BindingFlags.NonPublic | BindingFlags.Instance)?
            .GetValue(outputBindingsInfo);

        // Assume the complex type has a HttpResponseData-field named "HttpResponse"
        if (outputPropertyNames != null && outputPropertyNames.Contains("HttpResponse"))
        {
            var outputBindings = (Dictionary<string, object>)bindingFeatureType
                .GetProperty("OutputBindingData")!
                .GetValue(functionBindingsFeature)!;
            outputBindings.Add("HttpResponse", response);
        }
        // No output bindings defined
        else
        {
            context.GetInvocationResult().Value = response;
        }
    }
}
   
```
This assumes that the functions returns a complex type like this:

```
public class AuthorizationResponse
{
    [CosmosDBOutput(....)] // Or whatever
    public MyDocumentType MyDocument { get; set; }
    public HttpResponseData HttpResponse { get; set; } // <-- must be named "HttpResponse"
}
```

Any middleware wanting to override the output can then do some like:

```
var request = await context.GetHttpRequestDataAsync();
var response = request.CreateResponse();
await response.WriteAsJsonAsync( .... );
context.SetInvocationResult(response);
```

**Comment by kshyju** [comment]
> This is broken for the composite function return value. I am trying to craft an authorization middleware that short circuits HTTP requests and invoking this
> 
> ```
> var response = httpRequestData.CreateResponse(HttpStatusCode.Forbidden);
> context.GetInvocationResult().Value = response;
> ```
> 
> having function returning composite return for multiple bindings results in **200** always, e.g.
> 
> ```
>         return new ComplexResponse
>         {
>             HttpResponse = ...
>             ServiceBusResponse = ...
>         };
> ```

This is fixed now and will be available in the next preview version of worker package we will publish (hopefully next week). Once the package is out, I will share an example of how to handle this use case.

**Comment by kshyju** [comment]
For handling composite response type, please refer [this sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/ExceptionHandlingMiddleware.cs). You need [worker package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) 1.9.0 or above to get this fix.

**Comment by chancie86** [comment]
> Took another look at the issue. You are not getting the desired behavior(404 status code for http response and exception message as the body of the response) because you are not using the correct return type for your http trigger function. You are using `void` as the return type for the `ThrowException` method. If you want to return a valid http response from your function, you should use [HttpResponseData](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httpresponsedata?view=azure-dotnet) as the return type of your function.
> 
> The below code should work.
> 
> ```
> [Function("ThrowException")]
> public HttpResponseData ThrowException(
>     [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception")] HttpRequestData req)
>     => throw new System.Exception("Test message");
> ```
> 
> My previous comment was based on testing with the incorrect function code(with void as return type) 🤦
> 
> Let us know if you still run into issues. We will consider adding an analyzer to prevent users from using incorrect return types, in the future.

I also ran into this issue with the odd behaviour when return type was null. It left me scratching my head for quite a while. I agree, it's very unintuitive!

**Comment by Alan-Hinton** [comment]
This issue has be marked as closed, but I believe the original issue still exists.  I have updated my [minimal example](https://github.com/resgroup/azure-functions-middleware-status-code) to all the latest packages and copied the changes from the sample.  But I am still seeing the same behaviour: if an http triggered functions with `void`  or bare `Task` return type throws an exception the request results in a 200 response and the whole http response is returned as json.

i.e. this request returns the wrong status code and response
```
C:\Code>curl "http://localhost:7071/api/throw-exception" -H "accept: */*" -d "" -v
*   Trying 127.0.0.1:7071...
* Connected to localhost (127.0.0.1) port 7071 (#0)
> POST /api/throw-exception HTTP/1.1
> Host: localhost:7071
> User-Agent: curl/7.83.1
> accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 208
< Content-Type: application/json; charset=utf-8
< Date: Wed, 19 Oct 2022 19:33:06 GMT
< Server: Kestrel
<
{"method":"","query":{},"statusCode":"500","headers":{"Content-Type":"application/json; charset=utf-8"},"enableContentNegotiation":false,"cookies":[],"body":"eyJGb29TdGF0dXMiOiJJbnZvY2F0aW9uIGZhaWxlZCEifQ=="}* Connection #0 to host localhost left intact
```
whereas the endpoint that has a non-void return type gives the correct 500 response
```
C:\Code>curl "http://localhost:7071/api/throw-exception-and-return/true" -H "accept: */*" -d "" -v
*   Trying 127.0.0.1:7071...
* Connected to localhost (127.0.0.1) port 7071 (#0)
> POST /api/throw-exception-and-return/true HTTP/1.1
> Host: localhost:7071
> User-Agent: curl/7.83.1
> accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=utf-8
< Date: Wed, 19 Oct 2022 19:35:16 GMT
< Server: Kestrel
< Transfer-Encoding: chunked
<
{"FooStatus":"Invocation failed!"}* Connection #0 to host localhost left intact
```
This very much seems like a bug.  There doesn't seem to be any reason I shouldn't be able to have a request with a `void` return type.

**Comment by LockTar** [comment]
@kshyju I think @Alan-Hinton is correct. Why isn't it possible to use a `void` or `Task` as return type?

I've updated @Alan-Hinton sample project with extra test functions (see below) and all seem to work except `void` and `Task`.

So `HttpResponseData` is mandatory as return type if you don't have your own?

```C#
// Bug???
[Function("ThrowExceptionVoid")]
public void ThrowExceptionVoid(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception-void")] HttpRequestData req)
    => throw new System.Exception("Test message");

// Bug???
[Function("ThrowExceptionTask")]
public Task ThrowExceptionTask(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception-task")] HttpRequestData req)
    => throw new System.Exception("Test message");

// Correct expected behavoir
[Function("ThrowExceptionAndReturn")]
public MyResponseType ThrowExceptionAndReturn(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception-and-return/{returnUsefullData}")] HttpRequestData req,
    bool returnUsefullData)
    => returnUsefullData
        ? throw new System.Exception("Test message")
        : new MyResponseType();

// Correct expected behavoir
[Function("ThrowExceptionHttpResponseData")]
public HttpResponseData ThrowExceptionHttpResponseData(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception-httpresponsedata")] HttpRequestData req)
    => throw new System.Exception("Test message");

// Correct expected behavoir
[Function("ThrowExceptionTaskHttpResponseData")]
public Task<HttpResponseData> ThrowExceptionTaskHttpResponseData(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "throw-exception-task-httpresponsedata")] HttpRequestData req)
    => throw new System.Exception("Test message");
```

**Comment by kshyju** [comment]
@LockTar Can you open a new issue so we can discuss the current design and future plans there?

**Comment by kshyju** [comment]
See https://github.com/Azure/azure-functions-dotnet-worker/issues/1619#issuecomment-2223974185
